In [1]:
import pickle
import numpy as np
import pandas as pd

In [2]:
oheSex=pickle.load(open('trained_models/oheSex.pkl','rb'))
oheEmbarked=pickle.load(open('trained_models/oheEmbarked.pkl','rb'))
clf=pickle.load(open('trained_models/clf.pkl','rb'))

In [3]:
# pclass,sex,age,sibsp,fare,embarked 
input=np.array([3,'female',31,0,1,20,'S'],dtype=object).reshape(1,7)

In [7]:
input

array([[3, 'female', 31, 0, 1, 20, 'S']], dtype=object)

In [9]:
input_sex=oheSex.transform(input[:,1].reshape(1,1))


C:\Users\zulqa\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [13]:
input_sex

array([[1., 0.]])

In [15]:
input_embarked=oheEmbarked.transform(input[:,-1].reshape(1,1))

In [17]:
input_embarked

array([[0., 0., 1.]])

In [19]:
input_age=input[:,2].reshape(1,1)

In [21]:
input

array([[3, 'female', 31, 0, 1, 20, 'S']], dtype=object)

In [23]:
remaining_input=input[:,[0,3,4,5]]

In [25]:
remaining_input

array([[3, 0, 1, 20]], dtype=object)

In [27]:
input_transformed=np.concatenate((remaining_input,input_age,input_sex,input_embarked),axis=1)

In [29]:
input_transformed

array([[3, 0, 1, 20, 31, 1.0, 0.0, 0.0, 0.0, 1.0]], dtype=object)

In [35]:
clf.predict(input_transformed)

array([1], dtype=int64)