In [1]:
from sklearn.datasets import load_diabetes
import numpy as np
import pandas as pd 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [3]:
x,y = load_diabetes(return_X_y=True)

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [7]:
reg=LinearRegression()

In [9]:
reg.fit(x_train,y_train)

LinearRegression()

In [11]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [13]:
reg.intercept_

151.88331005254167

In [15]:
y_pred=reg.predict(x_test)

In [17]:
r2_score(y_test,y_pred)

0.4399338661568969

In [33]:
class SGDRegressor:
    def __init__(self,learning_rate=0.01,epochs=100):
        self.coef_=None
        self.intercept_ =None
        self.lr=learning_rate
        self.epochs=epochs

    def fit(self,x_train,y_train):
        self.intercept_=0
        self.coef_=np.ones(x_train.shape[1])
        for i in range(self.epochs):
            #updating value of intercept
           for j in range(self.epochs):
               idx= np.random.randint(0,x_train.shape[0])
               
               y_hat=np.dot(x_train[idx],self.coef_) + self.intercept_
               
               intercept_der = -2*(y_train[idx]-y_hat)
               self.intercept_= self.intercept_-(self.lr*intercept_der)

               coef_der = -2*np.dot((y_train[idx] - y_hat),x_train[idx]) 
               self.coef_ = self.coef_ - (self.lr * coef_der) 

        print(self.coef_,self.intercept_)

    def predict(self,x_test):
        return np.dot(x_test,self.coef_) + self.intercept_

In [35]:
sgdr= SGDRegressor(learning_rate=0.1,epochs=50)

In [37]:
sgdr.fit(x_train,y_train)

[  19.65855389  -87.34515399  406.15510404  271.30717712   22.8504209
  -39.24432677 -176.12612496  142.32164379  366.1408946   148.40374548] 117.51027176096147


In [39]:
y_pred= sgdr.predict(x_test)

In [41]:
r2_score(y_test,y_pred)

0.23024253347253454

In [46]:
from sklearn.linear_model import SGDRegressor

In [48]:
reg=SGDRegressor(learning_rate='constant',max_iter = 500,eta0=0.1)

In [50]:
reg.fit(x_train,y_train)

SGDRegressor(eta0=0.1, learning_rate='constant', max_iter=500)

In [52]:
pred=reg.predict(x_test)

In [54]:
r2_score(pred,y_test)

-0.2884247317885027

In [29]:
reg.coef_

array([  42.13209391, -107.41331347,  407.61050638,  280.2807734 ,
         -5.13968767,  -64.25394552, -185.55011949,  121.36848954,
        368.24902857,  122.03948099])

In [31]:
reg.intercept_

array([151.61307827])

In [236]:
sgdr.coef_

array([  36.8342503 ,  -83.9064362 ,  384.53978574,  277.53698113,
        -30.79981056,  -93.893436  , -190.40809574,  114.8550178 ,
        374.77191656,  147.00615299])